DROP DATABASE IF EXISTS GIFTDB;

CREATE DATABASE GIFTDB;

use GIFTDB;

CREATE TABLE Gifts (
    Id int NOT NULL AUTO_INCREMENT,
    GName varchar(255) UNIQUE NOT NULL,
    PRIMARY KEY (Id)
);
