DROP DATABASE IF EXISTS GIFTDB;

CREATE DATABASE GIFTDB;

use GIFTDB;

CREATE TABLE GIFT (
    GIFT_ID int NOT NULL AUTO_INCREMENT,
    GIFT_NAME varchar(255) UNIQUE NOT NULL,
    PRIMARY KEY (GIFT_ID)
);
